name: glopos
description: View elements in a global scene through local windows.
  Create effects which visually connect separate UI elements.
version: 0.1.0+1
homepage: https://github.com/blaugold/glopos/tree/main/packages/glopos
repository: https://github.com/blaugold/glopos
issue_tracker: https://github.com/blaugold/glopos/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
